using System;

namespace PE0002
{
    class Program
    {
        static void Main(string[] args)
        {
            /*
            Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
            */

            int waardeA = 1;
            int waardeB = 2;
            int resultaat = 0;

            for (int fibonacci = waardeA + waardeB; fibonacci < 4000000; fibonacci = waardeA + waardeB)
            {
                if (fibonacci % 2 == 0)
                {
                    resultaat += fibonacci;
                }
                waardeA = waardeB;
                waardeB = fibonacci;
            }
            Console.WriteLine(resultaat);
            Console.ReadLine();
            /*
            Dit geeft als resultaat 4613730.
            Dat antwoord werd afgekeurd.
            Ik besefte in het begin al dat het vraagstuk op twee manieren geïnterpreteerd kon worden:
            1. begin met waardes 1 en 2 (dus 4613730)
            2. Bepaal de som van alle even Fibonacci-getallen onder de vier miljoen (dus 4613732, want 2 is ook een even getal)
            Het tweede antwoord werd wel geaccepteerd.
            Bovenstaande code is van optie 1. Om optie 2 te verkrijgen vervang je "int waardeB = 2;" door "int waardeA = 1;".
            */

        }
    }
}
